import {Response} from 'express'
import Farmer from '../interfaces/Farmer'
import farmerModel from '../models/Farmer'
import {TypedRequestBody} from '../interfaces/TypedRequest'
import HttpResponse from '../utils/http-response'
